services:
  - type: web
    name: voice-masking-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd src/backend && python api_server.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000 